# Generated by Django 3.1.3 on 2020-11-13 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_label', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('fl_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('fl_address', models.TextField(default='', max_length=700)),
                ('fl_skills', models.CharField(default='', max_length=250)),
                ('fl_experience', models.IntegerField()),
                ('fl_education', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HireFreelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=250)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('profile_pic', models.CharField(default='', max_length=300)),
                ('freelancer', models.BooleanField(default=False)),
                ('seller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sl_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sl_address', models.TextField(default='', max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seller_set', to='pAuth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('sk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sk_label', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_pic',
            new_name='prod_pic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_category',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_description',
            field=models.TextField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_instruction',
            field=models.TextField(default='', max_length=700),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pAuth.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pAuth.product'),
        ),
        migrations.AddField(
            model_name='hirefreelancer',
            name='hired_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_by_hireFreelancer_set', to='pAuth.profile'),
        ),
        migrations.AddField(
            model_name='hirefreelancer',
            name='hired_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hired_to_hireFreelancer_set', to='pAuth.profile'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_freelancer_set', to='pAuth.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pAuth.profile'),
        ),
    ]
