# Generated by Django 3.1.3 on 2020-11-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pAuth', '0003_auto_20201114_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
